### ISSUE TITLE
OLAP MDX - Error

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid#1214]
Hi

I have managed to setup the olap datasource and able to connect to Essbase. However, when i execute the below query it is returning an exception. I can't work out the error thrown by SOAP. Hoping if you could assist me please?

Thanks

Query:
select x.col1, x.col2 as cbal from (call oacs.invokeMdx('SELECT [Year].Children ON 0,[Period].Children ON 1 FROM [FRC.FRC]')) w, ARRAYTABLE(w.tuple COLUMNS col1 string, col2 string) x;

Exception Stack:
2020-01-22 17:46:23,552 ERROR [org.teiid.CONNECTOR] (Worker1_QueryProcessorQueue24) jbIaCXNrNrI0 Connector worker process failed for atomic-request=jbIaCXNrNrI0.7.3.0: org.olap4j.OlapException: XMLA provider gave exception: <SOAP-ENV:Fault>
	
	<faultcode>
		SOAP-ENV: client
	</faultcode>
	
	<faultstring>
		<![CDATA[null]]>	</faultstring>
	
	<faultactor>
		XML for Analysis Provider for Essbase
	</faultactor>
	
</SOAP-ENV:Fault>

Request was:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <SOAP-ENV:Body>
    <Discover xmlns="urn:schemas-microsoft-com:xml-analysis"
        SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <RequestType>MDSCHEMA_PROPERTIES</RequestType>
    <Restrictions>
      <RestrictionList>
<CATALOG_NAME>FRC</CATALOG_NAME><SCHEMA_NAME></SCHEMA_NAME><CUBE_NAME>FRC.FRC</CUBE_NAME><DIMENSION_UNIQUE_NAME>[OrgUnit]</DIMENSION_UNIQUE_NAME><HIERARCHY_UNIQUE_NAME>[OrgUnit]</HIERARCHY_UNIQUE_NAME><LEVEL_UNIQUE_NAME>[OrgUnit].Levels(0)</LEVEL_UNIQUE_NAME>      </RestrictionList>
    </Restrictions>
    <Properties>
      <PropertyList>
        <DataSourceInfo>Provider=Essbase;Data Source=EssbaseCluster</DataSourceInfo>
        <Catalog>FRC</Catalog>
<LocaleIdentifier>2057</LocaleIdentifier>        <Content>Data</Content>
      </PropertyList>
    </Properties>
  </Discover>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
	at org.olap4j.driver.xmla.XmlaHelper.createException(XmlaHelper.java:35)
	at org.olap4j.driver.xmla.XmlaOlap4jConnection.executeMetadataRequest(XmlaOlap4jConnection.java:933)
	at org.olap4j.driver.xmla.XmlaOlap4jConnection.populateList(XmlaOlap4jConnection.java:851)
	at org.olap4j.driver.xmla.DeferredNamedListImpl.populateList(DeferredNamedListImpl.java:136)
	at org.olap4j.driver.xmla.DeferredNamedListImpl.getList(DeferredNamedListImpl.java:90)
	at org.olap4j.driver.xmla.DeferredNamedListImpl.size(DeferredNamedListImpl.java:116)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at org.olap4j.driver.xmla.XmlaOlap4jLevel.getProperties(XmlaOlap4jLevel.java:189)
	at org.olap4j.driver.xmla.XmlaOlap4jConnection$MemberHandler.addUserDefinedDimensionProperties(XmlaOlap4jConnection.java:1739)
	at org.olap4j.driver.xmla.XmlaOlap4jConnection$MemberHandler.handle(XmlaOlap4jConnection.java:1698)
	at org.olap4j.driver.xmla.XmlaOlap4jConnection.populateList(XmlaOlap4jConnection.java:854)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$RawMetadataReader.lookupMemberRelatives(XmlaOlap4jCube.java:547)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$RawMetadataReader.lookupMemberByUniqueName(XmlaOlap4jCube.java:438)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$RawMetadataReader.genericMembersLookup(XmlaOlap4jCube.java:525)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$RawMetadataReader.lookupMembersByUniqueName(XmlaOlap4jCube.java:471)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$DelegatingMetadataReader.lookupMembersByUniqueName(XmlaOlap4jCube.java:259)
	at org.olap4j.driver.xmla.XmlaOlap4jCube$CachingMetadataReader.lookupMembersByUniqueName(XmlaOlap4jCube.java:382)
	at org.olap4j.driver.xmla.XmlaOlap4jCellSet.populate(XmlaOlap4jCellSet.java:224)
	at org.olap4j.driver.xmla.XmlaOlap4jStatement.executeOlapQuery(XmlaOlap4jStatement.java:372)
	at org.teiid.translator.olap.OlapQueryExecution.execute(OlapQueryExecution.java:96)
	at org.teiid.dqp.internal.datamgr.ConnectorWorkItem.execute(ConnectorWorkItem.java:402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teiid.dqp.internal.datamgr.ConnectorManager$1.invoke(ConnectorManager.java:228)
	at com.sun.proxy.$Proxy43.execute(Unknown Source)
	at org.teiid.dqp.internal.process.DataTierTupleSource.getResults(DataTierTupleSource.java:302)
	at org.teiid.dqp.internal.process.DataTierTupleSource$1.call(DataTierTupleSource.java:108)
	at org.teiid.dqp.internal.process.DataTierTupleSource$1.call(DataTierTupleSource.java:104)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.teiid.dqp.internal.process.FutureWork.run(FutureWork.java:59)
	at org.teiid.dqp.internal.process.DQPWorkContext.runInContext(DQPWorkContext.java:281)
	at org.teiid.dqp.internal.process.ThreadReuseExecutor$RunnableWrapper.run(ThreadReuseExecutor.java:124)
	at org.teiid.dqp.internal.process.ThreadReuseExecutor$2.run(ThreadReuseExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2020-01-22 17:46:23,584 WARN  [org.teiid.PROCESSOR] (Worker2_QueryProcessorQueue25) jbIaCXNrNrI0 TEIID30020 Processing exception for request jbIaCXNrNrI0.7 'TEIID30504 oacs: XMLA provider gave exception: <SOAP-ENV:Fault>
	
	<faultcode>
		SOAP-ENV: client
	</faultcode>
	
	<faultstring>
		<![CDATA[null]]>	</faultstring>
	
	<faultactor>
		XML for Analysis Provider for Essbase
	</faultactor>
	
</SOAP-ENV:Fault>

Request was:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <SOAP-ENV:Body>
    <Discover xmlns="urn:schemas-microsoft-com:xml-analysis"
        SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <RequestType>MDSCHEMA_PROPERTIES</RequestType>
    <Restrictions>
      <RestrictionList>
<CATALOG_NAME>FRC</CATALOG_NAME><SCHEMA_NAME></SCHEMA_NAME><CUBE_NAME>FRC.FRC</CUBE_NAME><DIMENSION_UNIQUE_NAME>[OrgUnit]</DIMENSION_UNIQUE_NAME><HIERARCHY_UNIQUE_NAME>[OrgUnit]</HIERARCHY_UNIQUE_NAME><LEVEL_UNIQUE_NAME>[OrgUnit].Levels(0)</LEVEL_UNIQUE_NAME>      </RestrictionList>
    </Restrictions>
    <Properties>
      <PropertyList>
        <DataSourceInfo>Provider=Essbase;Data Source=EssbaseCluster</DataSourceInfo>
        <Catalog>FRC</Catalog>
<LocaleIdentifier>2057</LocaleIdentifier>        <Content>Data</Content>
      </PropertyList>
    </Properties>
  </Discover>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>'. Originally TeiidProcessingException XmlaHelper.java:35. Enable more detailed logging to see the entire stacktrace.

**Comment by yapnel** [comment]
It is an error on the Essbase dimension and Teiid OLAP has been configured correctly
