### ISSUE TITLE
vdb with oracle exception

### ISSUE THREAD

**Issue by superchenwei** [teiid/teiid#1267]
Hello:
      I encounter below exception when use oracle source in vdb;
     oracle version:11g
     ojdbc driver:ojdbc8.jar
    teiid info:teiid-wildfly-12.2.2-dist
     please help fix this,thank you!
```
Caused by: java.io.NotSerializableException: oracle.jdbc.driver.T4CConnection
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.teiid.client.BatchSerializer$ColumnSerializer.writeObject(BatchSerializer.java:591)
        at org.teiid.client.BatchSerializer$ObjectColumnSerializer.writeObject(BatchSerializer.java:267)
        at org.teiid.client.BatchSerializer$ArrayColumnSerializer2.writeObject(BatchSerializer.java:161)
        at org.teiid.client.BatchSerializer$ColumnSerializer.writeColumn(BatchSerializer.java:576)
        at org.teiid.client.BatchSerializer.writeBatch(BatchSerializer.java:909)
        at org.teiid.client.ResultsMessage.serialize(ResultsMessage.java:364)
        at org.teiid.client.ResultsMessage.writeExternal(ResultsMessage.java:328)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.teiid.net.socket.Message.writeExternal(Message.java:57)
        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.teiid.transport.ObjectEncoder.write(ObjectEncoder.java:112)
        ... 20 more

```

**Comment by shawkins** [comment]
This is due to the particular data that you have read.  There is something in your result that is not directly serializable - a struct perhaps, likely something that is typed as a teiid object.  That value is still referencing the Oralce connection and thus you are getting this exception.  You'll need to determine what the actual value type you are reading is, then we can determine a next step.
