### ISSUE TITLE
user hive datasource with kerberos in teiid

### ISSUE THREAD

**Issue by superchenwei** [teiid/teiid#1278]
Hello:
      I have some trouble when use hive datasource in teiid, below is exception info,need some help from your side,thank you
```
07:29:32,368 INFO  [org.teiid.RUNTIME.VDBLifeCycleListener] (MSC service thread 1-8)  TEIID40118 VDB hivetest.1 added to the repository
07:29:32,389 INFO  [org.teiid.RUNTIME] (MSC service thread 1-8)  TEIID50029 VDB hivetest.1 model "hivetest" metadata is currently being loaded. Start Time: 4/21/20 7:29 AM
07:29:32,590 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 65)  WFLYCLINF0002: Started client-mappings cache from ejb container
07:29:33,693 WARN  [io.undertow.servlet] (ServerService Thread Pool -- 68)  UT015020: Path /* is secured for some HTTP methods, however it is not secured for [TRACE, HEAD, DELETE, POST, GET, CONNECT, PUT]
07:29:33,725 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 68)  WFLYUT0021: Registered web context: '/odata4' for server 'default-server'
07:29:33,795 ERROR [stderr] (Worker0_async-teiid-threads0)  ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
07:29:34,055 INFO  [stdout] (Worker0_async-teiid-threads0-EventThread)  07:29:34.053 [Worker0_async-teiid-threads0-EventThread] ERROR org.apache.hive.org.apache.curator.ConnectionState - Authentication failed
07:29:34,915 INFO  [stdout] (Worker0_async-teiid-threads0)  07:29:34.908 [Worker0_async-teiid-threads0] ERROR org.apache.hive.org.apache.thrift.transport.TSaslTransport - SASL negotiation failure
07:29:34,917 INFO  [stdout] (Worker0_async-teiid-threads0)  javax.security.sasl.SaslException: GSS initiate failed
07:29:34,918 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[?:?]
07:29:34,920 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.org.apache.thrift.transport.TSaslClientTransport.handleSaslStartMessage(TSaslClientTransport.java:94) ~[hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,922 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,923 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,924 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,926 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,926 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
07:29:34,928 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_131]
07:29:34,929 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,930 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,931 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:239) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,932 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:194) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,933 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107) [hive-jdbc-2.1.0.2.6.4.0-91-standalone.jar!/:2.1.0.2.6.4.0-91]
07:29:34,934 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321) [ironjacamar-jdbc-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,935 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352) [ironjacamar-jdbc-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,940 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287) [ironjacamar-jdbc-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,942 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1325) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,943 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,943 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,944 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,945 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,946 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:440) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,947 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789) [ironjacamar-core-impl-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,948 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:151) [ironjacamar-jdbc-1.4.16.Final.jar!/:1.4.16.Final]
07:29:34,949 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64) [wildfly-connector-17.0.1.Final.jar!/:17.0.1.Final]
07:29:34,950 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.translator.jdbc.JDBCExecutionFactory.getConnection(JDBCExecutionFactory.java:281) [translator-jdbc-13.1.0.jar!/:13.1.0]
07:29:34,955 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.translator.jdbc.JDBCExecutionFactory.getConnection(JDBCExecutionFactory.java:70) [translator-jdbc-13.1.0.jar!/:13.1.0]
07:29:34,956 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.translator.ExecutionFactory.getConnection(ExecutionFactory.java:199) [teiid-api-13.1.0.jar!/:13.1.0]
07:29:34,957 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.query.metadata.NativeMetadataRepository.getMetadata(NativeMetadataRepository.java:65) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,958 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.query.metadata.NativeMetadataRepository.loadMetadata(NativeMetadataRepository.java:55) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,959 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.metadata.MetadataRepository.loadMetadata(MetadataRepository.java:41) [teiid-api-13.1.0.jar!/:13.1.0]
07:29:34,961 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.runtime.AbstractVDBDeployer$MetadataRepositoryWrapper.loadMetadata(AbstractVDBDeployer.java:88) [teiid-runtime-13.1.0.jar!/:13.1.0]
07:29:34,962 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.query.metadata.ChainingMetadataRepository.loadMetadata(ChainingMetadataRepository.java:51) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,963 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.runtime.AbstractVDBDeployer$2.run(AbstractVDBDeployer.java:291) [teiid-runtime-13.1.0.jar!/:13.1.0]
07:29:34,965 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.jboss.VDBService$6.run(VDBService.java:379) [teiid-wildfly-integration-13.1.0.jar!/:13.1.0]
07:29:34,966 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.dqp.internal.process.DQPWorkContext.runInContext(DQPWorkContext.java:281) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,970 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.dqp.internal.process.ThreadReuseExecutor$RunnableWrapper.run(ThreadReuseExecutor.java:124) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,970 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.teiid.dqp.internal.process.ThreadReuseExecutor$2.run(ThreadReuseExecutor.java:212) [teiid-engine-13.1.0.jar!/:13.1.0]
07:29:34,971 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
07:29:34,972 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
07:29:34,972 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
07:29:34,974 INFO  [stdout] (Worker0_async-teiid-threads0)  Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
07:29:34,975 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:343) ~[?:1.8.0_131]
07:29:34,976 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145) ~[?:1.8.0_131]
07:29:34,977 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[?:1.8.0_131]
07:29:34,978 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[?:1.8.0_131]
07:29:34,979 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[?:1.8.0_131]
07:29:34,979 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[?:1.8.0_131]
07:29:34,980 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) ~[?:1.8.0_131]
07:29:34,981 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) ~[?:?]
07:29:34,982 INFO  [stdout] (Worker0_async-teiid-threads0)      ... 40 more
07:29:34,987 INFO  [stdout] (Worker0_async-teiid-threads0)  Caused by: javax.security.auth.login.LoginException: PBOX00055: Failed to invoke CallbackHandler
07:29:34,987 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.security.auth.spi.UsernamePasswordLoginModule.getUsernameAndPassword(UsernamePasswordLoginModule.java:361) ~[picketbox-5.0.3.Final.jar!/:5.0.3.Final]
07:29:34,988 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.security.auth.spi.UsernamePasswordLoginModule.login(UsernamePasswordLoginModule.java:225) ~[picketbox-5.0.3.Final.jar!/:5.0.3.Final]
07:29:34,989 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.as.security.RealmDirectLoginModule.login(RealmDirectLoginModule.java:157) ~[wildfly-security-17.0.1.Final.jar!/:17.0.1.Final]
07:29:34,990 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
07:29:34,991 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
07:29:34,991 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
07:29:34,993 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
07:29:34,994 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_131]
07:29:34,995 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_131]
07:29:34,996 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_131]
07:29:34,996 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_131]
07:29:34,997 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
07:29:34,998 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_131]
07:29:35,002 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_131]
07:29:35,003 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSUtil.login(GSSUtil.java:258) ~[?:1.8.0_131]
07:29:35,005 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158) ~[?:1.8.0_131]
07:29:35,006 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335) ~[?:1.8.0_131]
07:29:35,007 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331) ~[?:1.8.0_131]
07:29:35,008 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
07:29:35,009 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330) ~[?:1.8.0_131]
07:29:35,009 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145) ~[?:1.8.0_131]
07:29:35,011 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[?:1.8.0_131]
07:29:35,011 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[?:1.8.0_131]
07:29:35,012 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[?:1.8.0_131]
07:29:35,013 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[?:1.8.0_131]
07:29:35,015 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) ~[?:1.8.0_131]
07:29:35,020 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) ~[?:?]
07:29:35,021 INFO  [stdout] (Worker0_async-teiid-threads0)      ... 40 more
16:03:41,025 INFO  [stdout] (Worker0_async-teiid-threads0)  Caused by: java.io.IOException: Cannot read from System.in
16:03:41,025 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.auth.callback.TextCallbackHandler.readLine(TextCallbackHandler.java:155) ~[?:?]
16:03:41,025 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.auth.callback.TextCallbackHandler.handle(TextCallbackHandler.java:120) ~[?:?]
16:03:41,026 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.security.auth.spi.UsernamePasswordLoginModule.getUsernameAndPassword(UsernamePasswordLoginModule.java:348) ~[picketbox-5.0.3.Final.jar!/:5.0.3.Final]
16:03:41,026 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.security.auth.spi.UsernamePasswordLoginModule.login(UsernamePasswordLoginModule.java:225) ~[picketbox-5.0.3.Final.jar!/:5.0.3.Final]
16:03:41,026 INFO  [stdout] (Worker0_async-teiid-threads0)      at org.jboss.as.security.RealmDirectLoginModule.login(RealmDirectLoginModule.java:157) ~[wildfly-security-17.0.1.Final.jar!/:17.0.1.Final]
16:03:41,026 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
16:03:41,026 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
16:03:41,027 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
16:03:41,036 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
16:03:41,037 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_131]
16:03:41,037 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_131]
16:03:41,037 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_131]
16:03:41,037 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_131]
16:03:41,038 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
16:03:41,039 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_131]
16:03:41,040 INFO  [stdout] (Worker0_async-teiid-threads0)      at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_131]
16:03:41,041 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSUtil.login(GSSUtil.java:258) ~[?:1.8.0_131]
16:03:41,041 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158) ~[?:1.8.0_131]
16:03:41,041 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335) ~[?:1.8.0_131]
16:03:41,042 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331) ~[?:1.8.0_131]
16:03:41,042 INFO  [stdout] (Worker0_async-teiid-threads0)      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
16:03:41,042 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330) ~[?:1.8.0_131]
16:03:41,042 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145) ~[?:1.8.0_131]
16:03:41,043 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[?:1.8.0_131]
16:03:41,049 INFO  [org.teiid.RUNTIME] (MSC service thread 1-8)  TEIID50012 Teiid JDBC - Name = jdbc, Host = 127.0.0.1,  Port = 31000, SSL = OFF
16:03:41,049 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[?:1.8.0_131]
16:03:41,050 INFO  [org.teiid.RUNTIME] (MSC service thread 1-3)  TEIID50037 Teiid ODBC - Name = odbc, Host = 127.0.0.1,  Port = 35432, SSL = OFF
16:03:41,050 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[?:1.8.0_131]
16:03:41,050 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[?:1.8.0_131]
16:03:41,050 INFO  [stdout] (Worker0_async-teiid-threads0)      at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) ~[?:1.8.0_131]
16:03:41,050 INFO  [stdout] (Worker0_async-teiid-threads0)      at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) ~[?:?]
16:03:41,051 INFO  [stdout] (Worker0_async-teiid-threads0)      ... 40 more 
```

**Comment by shawkins** [comment]
Is this happening when accessing the server from the client or when accessing the source?  It appears that you are not logged in and doNotPrompt is not set on the kerberos login module: https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/Krb5LoginModule.html

You'll get a better message with doNotPrompt=true, but it still means you likely have a problem with your other kerberos login module settings.

**Comment by superchenwei** [comment]
thank you
