### ISSUE TITLE
ClassNotFoundException for org.locationtech.jts.* with geometry Columns via Odata4

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [teiid/teiid#1315]
I am  running Teiid 13.1 as standalone server inside wildfly 17.0.1 via the current docker image jboss/teiid:latest (pulled 3 days ago).

When accessing a VDB containing some Geometry Colums via Odata4, I get the following error.
However the JTS jarfile seems to be present in the container (I found it in /opt/jboss/wildfly/modules/system/layers/dv/org/locationtech/jts/main  )

Meanwhile accessing the vdb via JDBC works fine, i can access spatial objects as well.

Any Ideas how this happens and how to resolve?
```
19:52:49,642 ERROR [org.teiid.ODATA] (default task-1)  TEIID16050 Unable to process odata request due to: org/locationtech/jts/geom/Point with cause org.locationtech.jts.geom.Point from [Module "org.jboss.teiid.olingo.common" version 13.1.0 from local module loader @29526c05 (finder: local module finder @2ef14fe (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/dv,/opt/jboss/wildfly/modules/system/layers/base))]: org.apache.olingo.server.api.ODataApplicationException: org/locationtech/jts/geom/Point

	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.TeiidServiceHandler.read(TeiidServiceHandler.java:174)
	at org.apache.olingo.server@4.7.1//org.apache.olingo.server.core.requests.DataRequest$EntityRequest.execute(DataRequest.java:335)
	at org.apache.olingo.server@4.7.1//org.apache.olingo.server.core.requests.DataRequest.execute(DataRequest.java:247)
	at org.apache.olingo.server@4.7.1//org.apache.olingo.server.core.ServiceDispatcher.internalExecute(ServiceDispatcher.java:166)
	at org.apache.olingo.server@4.7.1//org.apache.olingo.server.core.ServiceDispatcher.execute(ServiceDispatcher.java:97)
	at org.apache.olingo.server@4.7.1//org.apache.olingo.server.core.OData4HttpHandler.process(OData4HttpHandler.java:67)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.web.ODataServlet.service(ODataServlet.java:39)
	at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.web.ODataFilter.internalDoFilter(ODataFilter.java:287)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.web.ODataFilter.doFilter(ODataFilter.java:120)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.web.gzip.GzipFilter.doFilter(GzipFilter.java:57)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.web.CorsFilter.doFilter(CorsFilter.java:80)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Point
	at org.jboss.teiid.olingo.common@13.1.0//org.teiid.olingo.common.JTS2OlingoBridge.convert(JTS2OlingoBridge.java:47)
	at org.jboss.teiid.olingo.common@13.1.0//org.teiid.olingo.common.ODataTypeManager.convertToODataValue(ODataTypeManager.java:418)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.getPropertyValueInternal(EntityCollectionResponse.java:403)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.getPropertyValue(EntityCollectionResponse.java:347)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.buildPropery(EntityCollectionResponse.java:324)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.createEntity(EntityCollectionResponse.java:179)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.createEntity(EntityCollectionResponse.java:148)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.EntityCollectionResponse.addRow(EntityCollectionResponse.java:99)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.LocalClient.executeSQL(LocalClient.java:390)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.TeiidServiceHandler.executeQuery(TeiidServiceHandler.java:354)
	at org.jboss.teiid.olingo@13.1.0//org.teiid.olingo.service.TeiidServiceHandler.read(TeiidServiceHandler.java:168)
        ...63 more

Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.geom.Point from [Module "org.jboss.teiid.olingo.common" version 13.1.0 from local module loader @29526c05 (finder: local module finder @2ef14fe (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/dv,/opt/jboss/wildfly/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	...74 more

```

**Comment by shawkins** [comment]
> Any Ideas how this happens and how to resolve?

It's an issue with how the jboss modules are declared.  The jts dependency is under the org.jboss.teiid module.  The JTS2OlingoBridge is from the olingo module, which references the org.jboss.teiid module, but cannot directly use it's non-exported dependencies.  The fix will be to add org.locationtech.jts directly to the olingo module or to mark the jts module dependency as exported.

**Comment by shawkins** [comment]
This was resolved by https://issues.redhat.com/browse/TEIID-5996
However I also saw that https://issues.redhat.com/browse/TEIID-5997 was needed.
You may also be affected by https://issues.apache.org/jira/browse/OLINGO-1471

Released versions on the affected branches should be available in the next 2 weeks.

**Comment by sebastian-r-schmidt** [comment]
Excellent, thanks a lot for analyzing and fixing in less than one day :+1: . 

Patching the dependency Issue in my local environment works fine: I can export entitys containing geometry types, as long as I'm using JSON Output. 

After some more research I learned that XML Output is not implemented in Olingo v4 for Geometry types.
