### ISSUE TITLE
org.teiid.metadata.MetadataException: TEIID60011 No column found on table oracle.XDB.XDB$STATS with name "XMLDATA"."RESOID"

### ISSUE THREAD

**Issue by GavinRay97** [teiid/teiid#1381]
Hello =)

I have been experimenting with Teiid's embedded mode and everything seems to work well for multiple DB dialects, except for Oracle.
It seems like the column `oracle.XDB.XDB$STATS -> "XMLDATA"."RESOID"` does not exist (or it exists but there's nothing in it) on the Oracle DB I am testing with: 

![image](https://user-images.githubusercontent.com/26604994/155865245-1d50f9fb-603a-44b9-959f-d7701cd0a793.png)

![image](https://user-images.githubusercontent.com/26604994/155865794-89db564f-7e2e-429d-b5a8-621e2a66499f.png)

I am not familiar with Oracle at all (nearly all of my SQL experience is Postgres) so unsure whether this is unusual or not. Google doesn't turn up many results on this `"XMLDATA"."RESOID"` thing.

If it's helpful, below is the code I am using for testing:

```java
import org.hsqldb.jdbc.JDBCDataSource;
import org.postgresql.ds.PGSimpleDataSource;
import org.teiid.adminapi.impl.ModelMetaData;
import org.teiid.runtime.EmbeddedConfiguration;
import org.teiid.runtime.EmbeddedServer;
import org.teiid.translator.jdbc.hsql.HsqlExecutionFactory;
import org.teiid.translator.jdbc.oracle.OracleExecutionFactory;
import org.teiid.translator.jdbc.postgresql.PostgreSQLExecutionFactory;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.Properties;

public class JavaTeiidTest {

    public static void main(String[] args) throws Exception {
        Properties props = System.getProperties();
        props.setProperty("org.teiid.translator.jdbc.useFullSchemaNameDefault", "true");

        EmbeddedServer server = new EmbeddedServer();
        EmbeddedConfiguration config = new EmbeddedConfiguration();

        config.setUseDisk(false);
        server.start(config);

        JDBCDataSource hsqlDataSource = new JDBCDataSource();
        hsqlDataSource.setDatabase("jdbc:hsqldb:mem:test");
        initHSQLDB(hsqlDataSource);

        PGSimpleDataSource pgDataSource = new PGSimpleDataSource();
        pgDataSource.setUrl("jdbc:postgresql://localhost:5432/postgres");
        pgDataSource.setUser("postgres");
        pgDataSource.setPassword("postgres");

        oracle.jdbc.pool.OracleDataSource oracleDataSource = new oracle.jdbc.pool.OracleDataSource();
        oracleDataSource.setURL("jdbc:oracle:thin:@database-2.xxxxxxx.rds.amazonaws.com:1521:mydb");
        oracleDataSource.setUser("admin");
        oracleDataSource.setPassword("xxxxx");

        HsqlExecutionFactory hsqlExecutionFactory = new HsqlExecutionFactory();
        PostgreSQLExecutionFactory pgExecutionFactory = new PostgreSQLExecutionFactory();
        OracleExecutionFactory oracleExecutionFactory = new OracleExecutionFactory();

        hsqlExecutionFactory.start();
        pgExecutionFactory.start();
        oracleExecutionFactory.start();

        server.addTranslator("hsql-translator", hsqlExecutionFactory);
        server.addTranslator("pg-translator", pgExecutionFactory);
        server.addTranslator("oracle-translator", oracleExecutionFactory);

        server.addConnectionFactory("java:/hsql", hsqlDataSource);
        server.addConnectionFactory("java:/pg", pgDataSource);
        server.addConnectionFactory("java:/oracle", oracleDataSource);

        ModelMetaData hsqlModel = new ModelMetaData();
        ModelMetaData pgModel = new ModelMetaData();
        ModelMetaData oracleModel = new ModelMetaData();

        hsqlModel.setName("hsql");
        hsqlModel.addSourceMapping("hsql", "hsql-translator", "java:/hsql");

        pgModel.setName("pg");
        pgModel.addSourceMapping("pg", "pg-translator", "java:/pg");

        oracleModel.setName("oracle");
        oracleModel.addSourceMapping("oracle", "oracle-translator", "java:/oracle");

        server.deployVDB("vdb", hsqlModel, pgModel, oracleModel);
    }
}
```

```java
WARN: TEIID50036 VDB vdb.1 model "oracle" metadata failed to load. Reason:TEIID60011 No column found on table oracle.XDB.XDB$STATS with name "XMLDATA"."RESOID"
org.teiid.metadata.MetadataException: TEIID60011 No column found on table oracle.XDB.XDB$STATS with name "XMLDATA"."RESOID"
	at org.teiid.metadata.MetadataFactory.assignColumn(MetadataFactory.java:415)
	at org.teiid.metadata.MetadataFactory.assignColumns(MetadataFactory.java:546)
	at org.teiid.metadata.MetadataFactory.addPrimaryKey(MetadataFactory.java:322)
	at org.teiid.translator.jdbc.JDBCMetadataProcessor.getPrimaryKeys(JDBCMetadataProcessor.java:674)
	at org.teiid.translator.jdbc.JDBCMetadataProcessor.getConnectorMetadata(JDBCMetadataProcessor.java:216)
	at org.teiid.translator.jdbc.JDBCExecutionFactory.getMetadata(JDBCExecutionFactory.java:349)
	at org.teiid.translator.jdbc.JDBCExecutionFactory.getMetadata(JDBCExecutionFactory.java:110)
	at org.teiid.query.metadata.NativeMetadataRepository.getMetadata(NativeMetadataRepository.java:89)
	at org.teiid.query.metadata.NativeMetadataRepository.loadMetadata(NativeMetadataRepository.java:55)
	at org.teiid.query.metadata.ChainingMetadataRepository.loadMetadata(ChainingMetadataRepository.java:51)
	at org.teiid.runtime.AbstractVDBDeployer$2.run(AbstractVDBDeployer.java:291)
	at org.teiid.runtime.EmbeddedServer.runMetadataJob(EmbeddedServer.java:904)
	at org.teiid.runtime.AbstractVDBDeployer.loadMetadata(AbstractVDBDeployer.java:328)
	at org.teiid.runtime.AbstractVDBDeployer.loadMetadata(AbstractVDBDeployer.java:228)
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:852)
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:725)
	at com.example.JavaTeiidTest.main(JavaTeiidTest.java:92)
```

**Comment by GavinRay97** [comment]
As an update for anyone who runs across this in the future:

The fix is to explicitly set the importer filters for schema name and table types:
```java
oracleModel.setName("oracle");
oracleModel.addProperty("importer.schemaPattern", "SYSTEM");
oracleModel.addProperty("importer.tableTypes", "TABLE");
```

As far as I can tell, both of these are required. Removing the `tableTypes` clause gives the following error:
```java
Exception in thread "main" org.teiid.deployers.VirtualDatabaseException: TEIID40095 TEIID31071 Invalid table; Table oracle.SYSTEM.CATALOG has no columns defined
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:854)
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:725)
	at com.example.JavaTeiidTest.main(JavaTeiidTest.java:101)
```

Removing `schemaPattern` gives:
```java
Exception in thread "main" org.teiid.metadata.MetadataException: TEIID60011 No column found on table oracle.XDB.XDB$STATS with name "XMLDATA"."RESOID"
	at org.teiid.metadata.MetadataFactory.assignColumn(MetadataFactory.java:415)
	at org.teiid.metadata.MetadataFactory.assignColumns(MetadataFactory.java:546)
	at org.teiid.metadata.MetadataFactory.addPrimaryKey(MetadataFactory.java:322)
	at org.teiid.translator.jdbc.JDBCMetadataProcessor.getPrimaryKeys(JDBCMetadataProcessor.java:674)
	at org.teiid.translator.jdbc.JDBCMetadataProcessor.getConnectorMetadata(JDBCMetadataProcessor.java:216)
	at org.teiid.translator.jdbc.JDBCExecutionFactory.getMetadata(JDBCExecutionFactory.java:349)
	at org.teiid.translator.jdbc.JDBCExecutionFactory.getMetadata(JDBCExecutionFactory.java:110)
	at org.teiid.query.metadata.NativeMetadataRepository.getMetadata(NativeMetadataRepository.java:89)
	at org.teiid.query.metadata.NativeMetadataRepository.loadMetadata(NativeMetadataRepository.java:55)
	at org.teiid.query.metadata.ChainingMetadataRepository.loadMetadata(ChainingMetadataRepository.java:51)
	at org.teiid.runtime.AbstractVDBDeployer$2.run(AbstractVDBDeployer.java:291)
	at org.teiid.runtime.EmbeddedServer.runMetadataJob(EmbeddedServer.java:904)
	at org.teiid.runtime.AbstractVDBDeployer.loadMetadata(AbstractVDBDeployer.java:328)
	at org.teiid.runtime.AbstractVDBDeployer.loadMetadata(AbstractVDBDeployer.java:228)
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:852)
	at org.teiid.runtime.EmbeddedServer.deployVDB(EmbeddedServer.java:725)
	at com.example.JavaTeiidTest.main(JavaTeiidTest.java:101)
```

Hope someone finds this helpful in the future
