### ISSUE TITLE
Trying to upgrade wildfly

### ISSUE THREAD

**Issue by gadeynebram** [teiid/teiid#1402]
@rareddy @shawkins, I'd like to try and upgrade the wildfly server to a higher build.

I notice that there are references to the jboss-parent pom and also basepom-oss. Is there a link between jboss-parent and certain wildfly versions?

What would be a good strategy to try and perform these upgrades?

**Comment by Tom9729** [comment]
I'm also looking to update the Wildfly distribution to a newer version; ideally 27.

I tried to just hack something together and unpacked the Teiid modules on-top of the new Wildfly distribution (poor-man's Galleon). Unfortunately I got stuck because Wildfly 27 removes JBoss Security in favor of Elytron and the Teiid subsystem (`TeiidAdd.java`) has a dependency on classes in that module. I commented out the security integration and I'm able to get Wildfly to start up but I can't get it to recognize a VDB; Wildfly deploys it but it seems like the Teiid subsystem doesn't pick it up. I'm planning on going back a few Wildfly versions (maybe to 20?) to see where exactly this broke.

I think the link between the Wildfly and POM versions is that the Wildfly integration should use the same parent POM as the corresponding Wildfly server does. Currently Teiid used Wildfly 19 defined [here](https://github.com/teiid/teiid/blob/master/wildfly/pom.xml#L19). Note that POM uses jboss-parent 35, which is the same version that Wildfly 19 uses [here](https://github.com/wildfly/wildfly/blob/19.1.0.Final/pom.xml).

So I suspect to upgrade we'll want to change the Wildfly version property **and** lookup the version of the parent POM from the Wildfly repo, e.g. Wildfly 27 uses jboss-parent 39. Don't forget to also update the Wildfly Core and probably at least Jackson versions to match those bundled with the newer Wildfly.

**Comment by certara-dwebster** [comment]
@gadeynebram @Tom9729 
I have a fork of TEIID located at [https://github.com/Doug-Webster-Certara/teiid](https://github.com/Doug-Webster-Certara/teiid) which we have been modifying at Certara. This fork is currently at Wildfly v26.0.1 with the TEIID v17 codebase. We are going to move to v27.0.0 soon.
If you take this fork know that when we converted to Galleon packaging we moved the system/layers/dv modules down to the modules folder as we migrated and have not taken the time to move them back. Also, we have TEIID using Elytron but we did not have a usecase for certificate authentication so that aspect is missing. In addition, there are a few tweaks that we have made specific for Certara's use of TEIID including a change to keep Redshift from casting NULL to bpchar which causes a Redshift error 8001, and some changes to mitigate an Apache CXF error message when calling a webservice from the VDB.
I encourage you to review the changelog and take what you need from there if you want to migrate to Wildfly v26+ on your own fork.

**Comment by rareddy** [comment]
@Doug-Webster-Certara if you want to push this into the main branch we are open to it. We can get you to commit access to it. Then maybe we can release based on it.

**Comment by Tom9729** [comment]
Regarding my earlier comment about Teiid not picking the VDB up, it turned out to be my own fault. I had removed the REST WAR subsystem when trying to strip things down and forgot to remove the dependencies on the subsystem in the VDB service, so it was stuck waiting for that to deploy. After fixing that and integrating Doug's Elytron changes I was able to deploy my VDB on Wildfly 26 and run queries over JDBC. 👍 

Doug's branch currently has 60 commits. It will take a little work to clean things up to merge them into Teiid master. I think these are the main things that need to happen:

- Version change in POMs should be reverted back to 17.0.0-SNAPSHOT.
- Update the feature packs to move things back to `system/layers/dv`.
- It would be nice to separate out the unrelated bugfixes noted above and do a separate PR.

I also don't have a need for certificate authentication, just basic passwords. The OAuth-related login modules and I think a few other things (Kerberos?) are commented out and need updates to work with Elytron.

**Comment by certara-dwebster** [comment]
@rareddy @Tom9729 
If I can be granted access to push my changes into the teiid/teiid repository I have a branch prepared which has everything cleaned up and ready to reintegrate. The snapshot version is back to the expected 17.0.0-SNAPSHOT and the modules have been put back into system/layers/dv with the proper layers.conf file deployed.

**Comment by Tom9729** [comment]
@Doug-Webster-Certara thanks! 

I don't know what Ramesh will prefer but I think you should be able to create a pull request from your current branch into Teiid master without any special permissions. For example:

![image](https://user-images.githubusercontent.com/857047/210604036-f157c928-8e76-4696-b0da-d7a852329e8b.png)

Then Ramesh can review and maybe we can get a Travis CI build running, assuming that's still setup.

**Comment by rareddy** [comment]
Ok, I gave you both commit access. If you submit PR the Travis job should still run and let you know of any issues.

**Comment by certara-dwebster** [comment]
I have a PR created. https://github.com/teiid/teiid/pull/1405
I will wait to see what kind of feedback I get from the Travis job.

**Comment by Tom9729** [comment]
I'm looking through the PR and will try to do some testing in a VM locally later today. I think Travis only runs unit tests and we don't have any automated testing with real databases.

**Comment by Tom9729** [comment]
@rareddy how do we kick off Travis CI? Does it only run if the branch in the PR is in this repo?

**Comment by rareddy** [comment]
I was thinking we had build turned on PR submission but maybe it only runs after merging into master.

**Comment by HoldYourWaffle** [comment]
Has there been any progress on upgrading Teiid to recent versions of WildFly?
I just found out about this amazing project, but running a 3 year old version of WildFly makes me a little nervous.

**Comment by rareddy** [comment]
A little new version of the Wildfly can be found on this PR https://github.com/teiid/teiid/pull/1405 

> running a 3 year old version of WildFly makes me a little nervous.

unfortunately, we are operating totally on community contributions as we lost our corporate sponsorship to the project couple of years ago.

**Comment by HoldYourWaffle** [comment]
Oh wow, that is really unfortunate.
I would love to contribute to the community effort, but I have next to no experience in the "web-server" part of the Java ecosystem.

There seems to be significant progress in moving to WildFly 26 in #1405, but as far as I can tell it's not quite ready.
Perhaps @Doug-Webster-Certara or @Tom9729 could shed some light on this, what still needs to be done?
I tried building the branch myself, but I got a bunch of dependency errors that I haven't had a chance to investigate yet :(

Out of curiosity, what causes the incompatibility with newer WildFly versions?
Did they make some horrible breaking changes, or is Teiid perhaps too tightly coupled?

**Comment by rareddy** [comment]
Apply this https://github.com/rareddy/teiid/commit/a587af26e0c7bd3d58daeaa55ec0b3ce50216ac9 on top of Doug's PR the conflicts will be cleared. The later versions of WildFly choose a different "module" packaging system that is breaking change thus so many changes each connector is designed as independent components in Teiid.

**Comment by Tom9729** [comment]
> Did they make some horrible breaking changes, or is Teiid perhaps too tightly coupled?

They replaced the legacy security subsystem (Picketbox/Picketlink) with a new one called Elytron which required a bunch of changes. They also changed how the modules were packaged, as Ramesh already mentioned.

I can't speak to the level of coupling. I think the Wildfly integration has been pretty stable over the years; this was a big breaking change that affected anyone using Wildfly.

> what still needs to be done?

Even with Ramesh's patch, I think the full suite of unit tests are not passing. Specifically there is an error in the Infinispan integration that I don't know how to resolve. See the PR for details.

The hold-up for me is that I have the parts of Teiid I *actually* use working with Wildfly 26 in a custom build, so it's hard for me to justify spending time getting the remaining pieces working to the point where we could do a proper release.

If you would like to help out I suggest creating a new PR with Doug's changes, include Ramesh's commit, and then run the Maven build and try to work through the broken tests. I'm happy to review the PR, I just don't have a lot of time to investigate issues and submit changes.

**Comment by rareddy** [comment]
@Tom9729 Last I checked only one test was failing in Infinispan.

**Comment by antoniolucasnobar** [comment]
Hello folks, how are you?

I am trying to continue this work, but I need some assistance.

I made a fork of the teiid, master branch, and I was able to build the project with this command (found in README).

`mvn clean install -P dev,wildfly -s settings.xml`

However, when I tried to run tests, I had errors in TestParquetExecution. I ran this command:

`mvn -P arquillian-tests,wildfly test -B -s settings.xml -rf :translator-parquet` 
I used -rf :translator-parquet only to show the error. This was the first test that failed. 

`
[ERROR] Tests run: 22, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 13.768 s <<< FAILURE! - in org.teiid.translator.parquet.TestParquetExecution
[ERROR] org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithPathFilter  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: null partition value not expected
        at org.teiid.translator.parquet.TestParquetExecution.helpExecute(TestParquetExecution.java:39)
        at org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithPathFilter(TestParquetExecution.java:114)

[ERROR] org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithNestedPartitionFilter  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: null partition value not expected
        at org.teiid.translator.parquet.TestParquetExecution.helpExecute(TestParquetExecution.java:39)
        at org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithNestedPartitionFilter(TestParquetExecution.java:137)

[ERROR] org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithDirectoryBasedPartitioningAndPartitionedColumnSelect  Time elapsed: 0.016 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[[Michael, [2019], [Anne, 2019]]]> but was:<[[Michael, [null], [Anne, null]]]>
        at org.teiid.translator.parquet.TestParquetExecution.testParquetExecutionWithDirectoryBasedPartitioningAndPartitionedColumnSelect(TestParquetExecution.java:222)
`

I created a branch (wildfly26patches) to apply the patches from @certara-dwebster e @rareddy. I also tried to update apache parquet version, but these tests still fail. I looked the parquet file and it has all columns with data (month and year), but when the columns are partitions, the selects always returns null for them. I tried to use the same parquet file only with year as a partition and, in this test I did, the month returned correctly, but the year remained null.

Can you folks point me a direction? The commands I used are correct? Should I use the master branch as the starting point?

I looked over the @Tom9729 fork of teiid and it has a lot more commits and files changed. Is this a better place to start?

I wonder if I can update jacoco's dependency. Today is 0.8.3, which does not support java 17. I can go to 0.8.8 (first version with java 17 support) or even 0.8.10 (latest version), but 0.8.9+ requires Java 11 and I do not know if I can make this change.

Thanks in advance for your attention,
A. Lucas

**Comment by certara-dwebster** [comment]
@antoniolucasnobar ,

I am not sure what to suggest as your starting point. The latest code on https://github.com/certara-dwebster/teiid.git now has TEIID migrated to Wildfly 27.0.1.Final.
That migration can be built using Java 17 and is now on the Jakarta EE. 
It does require two dependencies to be built:
https://github.com/certara-dwebster/oreva.git  -  Using Java 11
https://github.com/certara-dwebster/olingo-odata4.git  -  Using Java 17

The tests for certain translators are also failing on this fork. Like you I do not have the experience needed to migrate these unit tests. This is a big transition as I am trying to keep TEIID running in later versions of Wildfly. Wildfly version 30.0.0 will be released soon and I will be falling further behind.
